version: '{build}'
os: Visual Studio 2022
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
  Cap_MySql_ConnectionString: Server=localhost;Database=cap_test;Uid=root;Pwd=Password12!;Allow User Variables=True;SslMode=Required
init:
  - ps: Start-Service MySQL80
before_build:
  - ps: dotnet tool install --global FlubuCore.Tool --version 8.0.0
build_script:
  - ps: flubu
test: off
artifacts:
- path: artifacts/**
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: 5f4zgyk7uMC3OCMFTKYGPj5Txw13s+KkY8vGXerg1Ad1vEQsDBe9arRv1PjhYQmR
  skip_symbols: false
  artifact: /artifacts\/.+\.s?nupkg/
